### PR TITLE
Fix #1: mismatched response length

### LINKED ISSUE #1: Mismatched response length
I got this error:

```
Mismatched response length. Expected 1 receipts but only received 2
```

This happens when send a single message with 3 receivers.

Errors appears on line:
https://github.com/9ssi7/exponent/blob/b983becf9f32cca14bb7f9efd03fdfb375e297f2/client.go#L88

This could be fixed 

Linked to original project issue : https://github.com/oliveroneill/exponent-server-sdk-golang/issues/12

Thanks

### PR DESCRIPTION
**Pull request by Fimeo**
The last fix seems to pose a problem

In the case of a payload containing several recipients, the line

https://github.com/9ssi7/exponent/blob/f2c95e8d8da3f810a2e8a559eca1f627f6a33f56/client.go#L95

causes an index out of bouds when adding message items in each response object.

Match each MessageItem with the response id.

According to the [expo documentation](https://docs.expo.dev/push-notifications/sending-notifications/#push-tickets), the output order of push token receipts is guaranteed by following the order of the messages in the input payload.

This merge request offers a solution issue #1 on mismatched response length.

The signature of the push single method had to be adapted to return an array of MessageResponse (one for each recipient of the Message).

Also fixes the NewClient with nil argument to avoid panic on nil pointer exception.

Update readme to match new function signature.

Contains breaking changes on push single method.

Thanks

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -101,5 +112,5 @@ func checkStatus(resp *http.Response) error {
 	if resp.StatusCode >= http.StatusOK && resp.StatusCode <= 299 {
 		return nil
 	}
-	return fmt.Errorf("invalid response (%d %s)", resp.StatusCode, resp.Status)
+	return fmt.Errorf("invalid response (%d %s)")
```
Comment (salihdev0) [inline client.go]: please remove `(%d %s)`

**Review by salihdev0 — CHANGES_REQUESTED** [review]
Super except for a small change. Thanks for your contribution

File: client.go (hunk 1 above)
Comment (Fimeo) [reply client.go]: Nice catch thanks

**Review by salihdev0 — APPROVED** [review]
